theme: jekyll-theme-cayman

title: Few-shot Learning for CT Scan based COVID-19 Diagnosis
description: A novel COVID-19 CT based diagnostic method can effectively utilize synthetic CT scans to boost COVID-19 diagnostic performance. (Accepted by ICASSP2021.)
